## NumPy array operations

In [2]:
import numpy as np

In [12]:
arr = np.arange(10)
print("Basic slicing: ", arr[2:6])
print("With steps: ", arr[2:6:2])
print("Negative Index: ", arr[-9:-5])

Basic slicing:  [2 3 4 5]
With steps:  [2 4]
Negative Index:  [1 2 3 4]


In [23]:
arr_2d = np.array([[1,2,3], [4,5,6], [7,8,9]])
print("Normal 2d array: ", arr_2d)

print("Specific element: ", arr_2d[1, 2])
print("Whole row: ", arr_2d[1])
print("Entire column: ", arr_2d[:, 2])

Normal 2d array:  [[1 2 3]
 [4 5 6]
 [7 8 9]]
Specific element:  6
Whole row:  [4 5 6]
Entire column:  [3 6 9]


### Sorting

In [55]:
unsorted  = np.array([3,4,12,3,234,23,2,11,1,2])
print("Sorted array: ", np.sort(unsorted))

unsorted_2d  = np.array([[5,1,6], [10, 2, 5], [2,5,1]])
print("Sorted 2D array by column: ", np.sort(unsorted_2d, axis=0))
print("Sorted 2D array by row: ", np.sort(unsorted_2d, axis=1))

Sorted array:  [  1   2   2   3   3   4  11  12  23 234]
Sorted 2D array by column:  [[ 2  1  1]
 [ 5  2  5]
 [10  5  6]]
Sorted 2D array by row:  [[ 1  5  6]
 [ 2  5 10]
 [ 1  2  5]]


### Filtering

In [63]:
numbers = np.arange(4, 12)
even_num = numbers[numbers % 2 == 0]
odd_num = numbers[numbers % 2 != 0]
print("Even numbers: ", np.sort(even_num))
print("Odd numbers: ", np.sort(odd_num))


Even numbers:  [ 4  6  8 10]
Odd numbers:  [ 5  7  9 11]


### Filter with mask

In [65]:
mask = numbers > 5 # expression that evaluates
print("Numbers greater than 5: ", numbers[mask])

Numbers greater than 5:  [ 6  7  8  9 10 11]


### Fancy indexing

In [ ]:
indices = [0,2,4]
print(numbers[indices])

# where clause 
where_res = np.where(numbers > 5) # actually it stores indices
print("NP Where: ", numbers[where_res])

[4 6 8]
NP Where:  [ 6  7  8  9 10 11]


In [72]:
conditional_arr = np.where(numbers > 5, numbers * 2, numbers)
print("Conditional arr: ", conditional_arr)

Conditional arr:  [ 4  5 12 14 16 18 20 22]


### Adding and removing data | Merging

In [ ]:
arr1  = np.array([1,2,3])
arr2  = np.array([4,5,6])

# combined_arr = arr1 + arr2 # this will add adjacent elements but we want to merge them
combined_arr = np.concatenate((arr1, arr2)) # don't miss.. tuple input

print("Combined array: ", combined_arr)

Combined array:  [1 2 3 4 5 6]


### array compatibility  - like same shape/size 

In [81]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])

print("Compatibility shapes: ", a.shape == b.shape == c.shape)

Compatibility shapes:  True


### adding a new row

In [90]:
original = np.array([[1,2], [3,4]])
new_row = np.array([5,6])

with_new_row = np.vstack((original, new_row))
print(original)
print(with_new_row)

new_col = np.array([[7],[8], [9]])
with_new_col = np.hstack((with_new_row, new_col))
print(with_new_col)


[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 7]
 [3 4 8]
 [5 6 9]]


### Deletion

In [92]:
arr = np.array([2,4,5,1,2,4,5])
deleted = np.delete(arr, 2) # index to remove
print("Array after deletion: ", deleted)


Array after deletion:  [2 4 1 2 4 5]
