## NumPy basics

In [1]:
import numpy as np

### creating array from list

In [9]:
arr_1d = np.array([1,2,3,4,5])
print("1D array:", arr_1d)

arr_2d = np.array([[1,2,3,4], [5,6,7,8]])
print("2D array: ", arr_2d)

1D array: [1 2 3 4 5]
2D array:  [[1 2 3 4]
 [5 6 7 8]]


### List vs NumPy array

In [ ]:
py_list = [1,2,3,4]
print("Python list multiplication: ", py_list * 2)

py_arr = np.array([1,2,3,4]) # element wise multiplication
print("Python array multiplication: ", py_arr * 2) # 2 is called scaler here.. just a fancy name

Python list multiplication:  [1, 2, 3, 4, 1, 2, 3, 4]
Python array multiplication:  [2 4 6 8]


#### Time difference

In [ ]:
import time

start = time.time()
py_list = [i*2 for i in range(10000000)]
print("\n List operation time: ", time.time() - start)

start = time.time()
np_arr = np.arange(10000000) * 2
print("\n Numpy array operation time: ", time.time() - start)


 List operation time:  0.9188661575317383

 Numpy array operation time:  0.024236440658569336


### Creating arrays from scratch

In [20]:
zeros = np.zeros((4,4))
print(zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [22]:
ones = np.ones((4,4))
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [25]:
full = np.full((2,8), 7)
print("Full array: \n", full)

Full array: 
 [[7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7]]


In [30]:
# random = np.random it is a class
random = np.random.random((2, 5))
random

array([[0.04216293, 0.52762872, 0.01942564, 0.16593467, 0.06251403],
       [0.75980412, 0.70968144, 0.96324147, 0.43546087, 0.90189076]])

In [37]:
# range in python is non-inclusive for end 
sequence = np.arange(0, 7, 3) # start, end, step
sequence


array([0, 3, 6])

### Vector, Matrix, Tensor

In [46]:
vector = np.array([1,2,3])
print("Vector: \n", vector) # 1D

matrix = np.array([ # 2D
    [1,2,3], 
    [5,6,7]
    ])
print("Matrix: \n", matrix)

tensor = np.array([ # Multi-D
    [[1,2], [3,4]], 
    [[5,6], [7,8]]
    ])
print("Tensor: \n", tensor)

Vector: 
 [1 2 3]
Matrix: 
 [[1 2 3]
 [5 6 7]]
Tensor: 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array properties

In [63]:
arr = np.array([[1,2,3,4], [5,6,7,8]])

# shape - rows and columns
print("Shape: ", arr.shape)

# Dimensions
print("Dimension: ", arr.ndim)

# Size
print("Dimension: ", arr.size)

# D TYpe
print("Data type: ", arr.dtype) 

# changing data changes datatype .. it is recommended to keep same data in an array of same type
arr = np.array([[1,2,3,4], [5,6,7,8]]) # datatype -> int64
arr = np.array([[1,2,3,4], [5,6,7,8.1]]) # datatype -> float64
arr = np.array([[1,2,3,4], [5,6,7,"1.2"]]) # datatype -> <U21 - unicode with max length of 21 .. can change if length goes beyond 21 


Shape:  (2, 4)
Dimension:  2
Dimension:  8
Data type:  int64


### Array reshaping

In [73]:
arr = np.arange(12)
print("Original array: ", arr)

reshaped = arr.reshape((3,4))
print("Original array: ", reshaped)

flattened = reshaped.flatten()
print("Flattened array: ", flattened)

# ravel return a view instead of a copy
raveled = reshaped.ravel()
print("Raveled array: ", raveled)

# Transpose
transpose = reshaped.T
print("Transpose array: ", transpose)

Original array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Original array:  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transpose array:  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
